server {
    listen 80;

    # 1. Servir la Web (Frontend compilado)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Importante para que al recargar no de error 404
    }

    # 2. Redirigir llamadas de API al Backend (Python)
    # Tu frontend llama a "/api/items", Nginx lo convierte en "/items" y lo manda a Python
    location /api {
        proxy_pass http://backend:8000;
        rewrite ^/api/(.*) /$1 break; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}